import type { Metadata } from "next";
import "./globals.css";
import Wallet from "./wallet";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <div className="flex min-h-screen w-full divide-x divide-gray-700 align-center">
                    <Wallet />
                    <div className="flex flex-col grow h-screen overflow-y-auto">
                        {children}
                    </div>
                </div>
            </body>
        </html>
    );
}
